# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   # app.login_listener:
    #    class: ConfigBundle\Listener\LoginListener
    #    arguments: [ "@security.context", "@router" ,"@session"]
    #    tags:
    #    - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    #    - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse  }

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']